-- Migrar datos existentes de clients a client_projects
INSERT INTO public.client_projects (
  client_id,
  project_name,
  project_description,
  budget,
  timeline_months,
  land_square_meters,
  service_type,
  project_type,
  status,
  sales_pipeline_stage,
  priority,
  estimated_value,
  probability_percentage,
  conversion_date,
  last_contact_date,
  next_contact_date,
  last_activity_date,
  location_details,
  payment_plan,
  conversion_notes,
  notes,
  tags,
  assigned_advisor_id,
  branch_office_id,
  alliance_id,
  lead_referral_details,
  curp,
  created_at,
  updated_at
)
SELECT 
  id as client_id,
  'Proyecto Principal - ' || full_name as project_name,
  'Proyecto migrado automáticamente' as project_description,
  budget,
  timeline_months,
  land_square_meters,
  service_type,
  project_type,
  status,
  sales_pipeline_stage,
  priority,
  estimated_value,
  probability_percentage,
  conversion_date,
  last_contact_date,
  next_contact_date,
  last_activity_date,
  location_details,
  payment_plan,
  conversion_notes,
  notes,
  tags,
  assigned_advisor_id,
  branch_office_id,
  alliance_id,
  lead_referral_details,
  curp,
  created_at,
  updated_at
FROM public.clients
WHERE budget IS NOT NULL OR status IS NOT NULL OR sales_pipeline_stage IS NOT NULL;