// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycbflvptfgrjclzzlxci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljYmZsdnB0ZmdyamNsenpseGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4Mjc3MTIsImV4cCI6MjA2OTQwMzcxMn0.heHlRyYZX2E18e_--bdgsDgMlBxC-O3K41KRmDZgnvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});